server:
  port: 8081

spring:
  application:
    name: auth-service
  
  threads:
    virtual:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/mini_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: true

# Tùy chọn cấu hình client REST để gọi sang wallet-service
app:
  services:
    wallet-url: http://localhost:8082
