server:
  port: 8086

spring:
  application:
    name: notification-service

  threads:
    virtual:
      enabled: true

  # Cấu hình Apache Kafka Consumer kết nối
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
